FROM python:3.9

RUN apt-get update && apt-get install -y cron

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# copy your cron file to the cron.d directory
COPY scripts/cronjobs /etc/cron.d/cronjobs

# give the file the appropriate permissions
RUN chmod 0644 /etc/cron.d/cronjobs

# apply the cron job
RUN crontab /etc/cron.d/cronjobs

CMD ["cron", "-f"]
